version: "3.3"

services:
  db:
    container_name: mysqlDB
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
  backend:
    container_name: backend
    image: oues1436/backend
    ports:
      - 8089:8089
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: oues1436/frontend
    ports:
      - 80:80
    depends_on:
      - backend