version: '3.5'
services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=genadminpwd
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    image: achat-backend
    container_name: achat-backend
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone