name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 */24 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: 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 
          # Options
          user: GNRain
          repo: ProjetCI-No-Name
          template: repository
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_traffic: yes
